[build-system]
build-backend = "setuptools.build_meta"
requires = [
	"setuptools>=61.0",
	"wheel",
]

[project]
authors = [
	{ name = "Matt Wilson", email = "matthew@synesis.com.au" },
]
dependencies = [
	"asyncio",
	"diagnosticism",
	"pytest>=8.4.1",
]
description = "Tokio-like functionality for Python"
license-files = ["LICENSE"]
name = "asynkio"
readme = "README.md"
requires-python = ">=3.11"
version = "0.0.1"

[project.urls]
Changelog = "https://github.com/synesissoftware/asynkio/releases"
Homepage = "https://github.com/synesissoftware/asynkio"
Issues = "https://github.com/synesissoftware/asynkio/issues"

[project.optional-dependencies]
dev = [
	"aiofiles",
	"pyclasp>=0.8.10",
	"pytest>=7.4.4",
]
test = [
	"aiofiles",
	"pyclasp>=0.8.10",
	"pytest>=7.4.4",
]

